apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: demos-ns
spec:
  replicas: 3
  
  selector:
    matchLabels:
      app: my-app  # This must match the labels in spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: ahouragorji/cloudproject:kube
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name : api_key1
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: API_KEY1
            - name: api_key2
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: API_KEY2
          ports:
            - containerPort: 8000 