apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: demos-ns
spec:
  capacity:
    storage: 1Gi  
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: manual
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/redis  
