apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: demos-ns
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None  