apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: demos-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data  
          envFrom:
            - configMapRef:
                name: app-config
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc  