apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: demos-ns
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi  
  storageClassName: manual 